export const projects = [
  {
    title: "Posgrados de la Provincia",
    accesibility: "",
    date: "2023 (In progress)",
    language: "Drupal",
    link: false,
  },
  {
    title: "Buenos Aires Crea",
    accesibility: "Go to Buenos Aires Crea website",
    date: "2022",
    language: "Vanilla",
    link: "https://buenosairescrea.gba.gob.ar",
  },
  {
    title: "Honorable Tribunal de Cuentas",
    accesibility: "",
    date: "2022 (In progress)",
    language: "Drupal",
    link: false,
  },
  {
    title: "Agenda Participativa",
    accesibility: "Go to Agenda Participativa website",
    date: "2022 (contributed)",
    language: "Drupal",
    link: "https://agendaparticipativa.gba.gob.ar/",
  },
  {
    title: "Qunitas",
    accesibility: "",
    date: "2023 (Contributed - In progress)",
    language: "Drupal",
    link: false,
  },
  {
    title: "Derecho al Futuro",
    accesibility: "Go to Derecho al Futuro website",
    date: "2022",
    language: "Drupal",
    link: "https://derechoalfuturo.gba.gob.ar",
  },
  {
    title: "Coderhouse Course Final Project",
    accesibility: "Go to project github",
    date: "2022",
    language: "React",
    link: "https://github.com/JordiBustos/adidas-JordiBustos",
  },
  {
    title: "Codigo Provincia",
    accesibility: "Go to Codigo Provincia website",
    date: "2022 (contributed)",
    language: "React",
    link: "https://codigoprovincia.gba.gob.ar/",
  },
  {
    title: "Style Transfer with NASA API",
    accesibility: "",
    date: "2022",
    language: "React",
    link: false,
  },
  {
    title: "Convert speech to excel with text",
    accesibility: "View on github",
    date: "2022",
    language: "Python",
    link: "https://github.com/JordiBustos/Speech-to-text",
  },
  {
    title: "Project Euler",
    accesibility: "View on github",
    date: "2022-2023",
    language: "JavaScript",
    link: "https://github.com/JordiBustos/Interview-Questions-Code/tree/master/ProjectEuler",
  },
  {
    title: "Scientific Computing",
    accesibility: "View on github",
    date: "2022",
    language: "Python",
    link: "https://github.com/JordiBustos/Interview-Questions-Code/tree/master/Numeric%20Computation",
  },
  {
    title: "Pascal's Triangle",
    accesibility: "View on github",
    date: "2022",
    language: "JavaScript",
    link: "https://github.com/JordiBustos/Interview-Questions-Code/tree/master/Take%20Home%20Projects/Pascal's%20Triangle",
  },
  {
    title: "Query Wikipedia API",
    accesibility: "View on github",
    date: "2023",
    language: "JavaScript",
    link: "https://github.com/JordiBustos/Interview-Questions-Code/tree/master/Take%20Home%20Projects/Wikipedia%20API",
  },
  {
    title: "Data Structures",
    accesibility: "View on github",
    date: "2023",
    language: "JavaScript",
    link: "https://github.com/JordiBustos/Interview-Questions-Code/tree/master/Data%20Structures",
  },
  {
    title: "Algorithms",
    accesibility: "View on github",
    date: "2023",
    language: "JavaScript",
    link: "https://github.com/JordiBustos/Interview-Questions-Code/tree/master/Algorithms",
  },
  {
    title: "Interview Questions",
    accesibility: "View on github",
    date: "2023",
    language: "JavaScript",
    link: "https://github.com/JordiBustos/Interview-Questions-Code",
  },
  {
    title: "Convex Hull O(n log n)",
    accesibility: "View on github",
    date: "2022",
    language: "TypeScript",
    link: "https://github.com/JordiBustos/Exercises/tree/master/Algorithms/Convex%20Hull",
  },
  {
    title: "Random Machine Learning Projects",
    accesibility: "View on github",
    date: "2023",
    language: "Python",
    link: "https://github.com/JordiBustos/GeneralProjects",
  },
  {
    title: "Random Data Science Projects",
    accesibility: "View on github",
    date: "2022",
    language: "Python",
    link: "https://github.com/JordiBustos/DataScience-ML",
  },
  {
    title: "Univariable Prediction using LSTM",
    accesibility: "View on github",
    date: "2022",
    language: "Python",
    link: "https://github.com/JordiBustos/prediccion-univariable",
  },
];
